export TERM="screen-256color"

alias pdf="zathura"

xrandr --output eDP1 --mode 1920x1080
xrandr --output DP1 --primary --auto --left-of eDP1

set -o vi

# added by Miniconda2 4.0.5 installer
export PATH="/opt/miniconda/bin:$PATH"

function catl { cat "$1" | less; }
export -f catl

function ll { 
	if [ $# -eq 0 ]
	then
		ls -la . | less;
	else
		ls -la "$1" | less;
	fi
}
export -f ll

alias gits="git status"
alias gitd="git diff"
alias gitchk="git checkout"
alias gitcm="git commit"

export VISUAL=vim
export EDITOR="$VISUAL"

function vup {
  local OPTIND OPT flags env
	while getopts "pe:" OPT
	do
		case "${OPT}" in
			p)
        flags="--provision"
				;;
			e)
				env=${OPTARG}
				;;
		esac
	done
  if ! [[ -v env ]]
  then
    env="dev"
  fi
 
  vagrant nsidc up "$flags" --env="$env"
}
export -f vup

function vdest {
  if [ $# -eq 0 ] 
  then
    vagrant nsdic destroy --env=dev
  else
    vagrant nsidc destroy --env="$1"
  fi
}
export -f vdest

export NVM_DIR="/home/trst2284/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# added by Miniconda3 4.1.11 installer
export PATH="/home/trst2284/miniconda3/bin:$PATH"
