" Begin Vundle Config
" Following required for Vundle Plugin Manager
set nocompatible
filetype off
" Set the runtime path to include Vundle & init
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Let vundle manage vundle
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/syntastic'
Plugin 'nvie/vim-flake8'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-fugitive'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'Yggdroot/indentLine'
Plugin 'flazz/vim-colorschemes'
" -----------------------------
" PLACE PLUGINS ABOVE THIS LINE
" Finish Vundle initialization
call vundle#end()
filetype plugin indent on
" End Vundle Config

set laststatus=2
"set showtabline=2
set noshowmode
augroup FastEscape
	autocmd!
	au InsertEnter * set timeoutlen=0
	au InsertLeave * set timeoutlen=1000
augroup END

" Automatic reloading of .vimrc
autocmd! bufwritepost .vimrc source %

" Turns on relative numbering by default
set relativenumber

" Highlights matching brackets/braces/parens
set showmatch

" Set color
set t_Co=256

" Remap Ctl-C in visual mode to Esc. This lets us leave visual quicker...
vnoremap <ESC> <C-c>
" Some config for vim-airline
let g:airline#extension#tabline#enabled = 1
let g:airline_powerline_fonts = 1

"Change split nav
nnoremap <C-J> <C-W><C-j>
nnoremap <C-K> <C-W><C-k>
nnoremap <C-L> <C-W><C-l>
nnoremap <C-H> <C-W><C-h>

" Change window movement nav
"noremap <C-S-J> <C-W><J>
"noremap <C-S-K> <C-W><K>
"noremap <C-S-L> <C-W><L>
"noremap <C-S-H> <C-W><H>
" File settings
" For Python
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |
    \ let python_highlight_all=1 |

" For js, html, and css:
au BufNewFile,BufRead *.js, *.html, *.css
	\ set tabstop=2 |
	\ set softtabstop=2 |
	\ set shiftwidth=2 |
	\ set autoindent |
	\ set fileformat=unix |

" Enable syntax highlighting?...
syntax on

" Enable utf-8 encoding
set encoding=utf-8

" A couple customizations to YouCompleteMe
" First, make sure suggestion closes after complete
let g:ycm_autoclose_preview_window_after_completion=1
" Second, map leader-g to goto definition
map <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
" Third, set the whitelist for this to work w/
let g:ycm_filetype_whitelist = {'cpp': 1, 'c': 1, 'python': 1, 'js': 1}

" Config for syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Config for NerdTree
let NERDTreeIgnore=['\.pyc$', '\~$']
map <C-n> :NERDTreeToggle<CR>

" Config indentLine
let g:indentLine_color_term = 239
let g:indentLine_char = '|'

"Try to set a colortheme
set background=dark
colorscheme zenburn 
" Enable syntax highlighting?...
syntax on
" Enable improved wildcards in command
set wildmenu

" Supress warning from switching between edited buffers
set hidden
set confirm

" Just trying out transparent background:
"hi Normal ctermbg=none
